### Default spring profile ###
info:
  app:
    name: @name@
    description: @description@
    version: @version@

server:
   port: 8090
   context-path: /marvel

spring:
  profiles:
    active: local
  application:
    name: ${info.app.name}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource

liquibase:
  changeLog: classpath:/db/changelog/db.changelog-master.xml

---
### Spring profile: local ###
spring:
  profiles: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/apc_local
    username: postgres
    password: postgres

logging:
  file: .\marvelapi.log
  level:
    ROOT: INFO
    com:
      eureka_labs: DEBUG

marvel:
  url: "http://gateway.marvel.com/v1/public/"
  key:
    public: "bbbf493d480bd0461dcfc0e55325ccf3"
    private: "08fa575658fd01eff7233e6d89ceb9a47097b1d7"

app:
  region: Local